### ISSUE TITLE
Fix swiper.js initialization in storybook

### ISSUE THREAD

**Issue by stephiescastle** [nasa-jpl/explorer-1#11]
Swiper.js doesn't initialize correctly on stories: initializes before the story is loaded--we need it to initialize after the story loads, and every time a relevant story loads.

**Comment by shiv19** [comment]
If anyone came here while trying to make Swiper Elements work with Storybook in an angular 15+ project,
I ended up adding `"skipLibCheck": true,` to the `.storybook/tsconfig.json` under compilerOptions.
With that storybook is working fine with Swiper.
