### ISSUE TITLE
Add BlockAccordion component

### ISSUE THREAD

**Issue by stephiescastle** [nasa-jpl/explorer-1#146]
### Describe the problem to be solved

Designlab has built an accordion component using the Explorer 1 design system, but the component has not been added to the design system yet, limiting its availability. 

### Suggested solution

Add BlockAccordion to the Explorer 1 design system:
- [ ] template
- [ ] styles
- [ ] js functionality
- [ ] stories
- [ ] icons

![image](https://user-images.githubusercontent.com/1588657/152862970-a902b8b5-604d-4e24-a069-8d0c2fc04c09.png)

**Comment by gekim84** [comment]
@Scotchester @stephiescastle @jamesray @rashmi-arjunan 
thoughts on using controls that I designed for the table?
https://www.figma.com/file/05Gjku1mbFGoqRrU1uwLCa/?node-id=1%3A19 
<img width="1024" alt="Screen Shot 2022-05-11 at 12 52 49 PM" src="https://user-images.githubusercontent.com/44758056/167934271-b805fe0f-f81d-4375-8c93-93bce32363f8.png">

So it might look like this:
<img width="995" alt="Screen Shot 2022-05-11 at 12 52 56 PM" src="https://user-images.githubusercontent.com/44758056/167934345-71d50fa7-3e98-4dc5-90dc-c7f491280a5e.png">

**Comment by Scotchester** [comment]
@gekim84 Feels a little unintuitive to me, to be honest.

**Comment by gekim84** [comment]
ok, we could just use what JPL Space uses:
https://www.figma.com/file/pkt0QLEc0TapRRPxa9RWDC/?node-id=1%3A19
<img width="731" alt="Screen Shot 2022-05-11 at 1 20 41 PM" src="https://user-images.githubusercontent.com/44758056/167940851-1af44c1c-8492-49fc-9ac3-b3f3a94aeb8a.png">
