### ISSUE TITLE
address `LayoutHelper` discrepancies

### ISSUE THREAD

**Issue by laespinoza** [nasa-jpl/explorer-1#40]
`LayoutHelper` comes from a nuxt component that uses props to determine which col-start- and col-end- classes to apply to the nested div. The `LayoutHelper` class isn't necessary here as it doesn't serve a purpose.

**Comment by stephiescastle** [comment]
We added additional helper classes and documented them in PR #277. Documentation is available on the [Column Layout Helpers page](https://nasa-jpl.github.io/explorer-1/?path=/docs/foundation-grid-and-layout-column-layout-helpers--base-width) in Storybook.
