### ISSUE TITLE
Remove top margin from headings that are the first child of `.BlockText

### ISSUE THREAD

**Issue by stephiescastle** [nasa-jpl/explorer-1#648]
Now that headings can be added in rich text, we're getting a double margin when they are the first element within `.BlockText`.

We need to remove the top margin of all headings that fit this use-case.

**Comment by Scotchester** [comment]
I think I added that top margin intentionally? I thought it was good back when we first added the ability to use headings in rich text, so I went back to look at my PRs. Take a look at #327.

Did some new margin get added elsewhere, perhaps?

**Comment by stephiescastle** [comment]
> I think I added that top margin intentionally? I thought it was good back when we first added the ability to use headings in rich text, so I went back to look at my PRs. Take a look at https://github.com/nasa-jpl/explorer-1/pull/327.

Yeah, it makes sense to add margins to headings within BlockText, but the issue is the margin on headings when they're the first child. You can see it happening here: https://www.jpl.nasa.gov/preview?content_type=information_pages.contentpage&token=id=131060:1swQ5C:19cXLl06EIeg3G75OaPz8vVFULWyQMDhECerNi-G5yw&path=/blended-worlds

**Comment by Scotchester** [comment]
Yeah, I just want to believe I would have thought to account for that before 😆 But very possible I did not.

**Comment by stephiescastle** [comment]
> Yeah, I just want to believe I would have thought to account for that before 😆 But very possible I did not.

Maybe the use-case at the time was predominantly wanting to add headings without stopping the flow of BlockText, and BlockHeading was always added first, separately?

**Comment by stephiescastle** [comment]
In code review https://github.com/nasa-jpl/explorer-1/pull/649
